import { useTranslation } from "next-i18next";
import NextLink from "next/link";

import { SEO } from "@/lib/meta";
import { BookingPanel } from "@/lib/bnovo";
import {
  Container,
  Footer,
  Header,
  Main,
  Promo,
  PromoContent,
  PromoTitle,
  StickyHeader,
} from "@/ui/layout";
import { Button, SearchButton } from "@/ui/inputs";
import {
  L_BREAKPOINT_DOWN,
  XL_BREAKPOINT_DOWN,
  S_BREAKPOINT_DOWN,
} from "@/config/breakpoints";
import { useMediaQuery } from "@/lib/media";
import { Title, Text } from "@/ui/data-display";

import promoImg from "@/assets/images/spb/promo.jpg";
import styles from "./HotelRulesSpb.module.css";

export const HotelRulesSpb = () => {
  const { t } = useTranslation("cities", {
    keyPrefix: "routes.hotelRulesSpb",
  });

  const isLaptop = useMediaQuery(XL_BREAKPOINT_DOWN);
  const isTablet = useMediaQuery(L_BREAKPOINT_DOWN);
  const isMobile = useMediaQuery(S_BREAKPOINT_DOWN);

  const textVariant = isTablet ? (isMobile ? "normalS" : "normalM") : "normalL";

  return (
    <>
      <SEO title={t("metaTitle")} />
      <Promo img={promoImg}>
        <Header>
          <SearchButton />
        </Header>
        <StickyHeader withBurgerMenu={false} />
        <PromoContent desktopCenter spacing="m">
          <PromoTitle
            order={isLaptop ? (isTablet ? 3 : 2) : 1}
            hasWidthLimit={false}
          >
            {t("title")}
          </PromoTitle>
        </PromoContent>
      </Promo>
      <Main>
        <BookingPanel />
        <Container>
          <div className={styles.container}>
            <div className={styles.wrapper}>
              <div className={styles.listWrapper}>
                <Title order={isLaptop ? (isTablet ? 4 : 3) : 2}>
                  {t("rules.title")}
                </Title>
                <Text color="secondary" variant={textVariant}>
                  {t("rules.text")}
                </Text>
                <ol>
                  <li className={styles.listEl}>
                    <Title order={4} className={styles.title}>
                      {t("rules.listTitle1")}
                    </Title>
                  </li>
                  <ol className={styles.listItem}>
                    <div className={styles.listDist}>
                      <li>{t("rules.listItem1-1")}</li>
                      <li>{t("rules.listItem1-2")}</li>
                      <li>{t("rules.listItem1-3")}</li>
                      <li>{t("rules.listItem1-4")}</li>
                      <li>{t("rules.listItem1-5")}</li>
                      <li>{t("rules.listItem1-6")}</li>
                      <li>{t("rules.listItem1-7")}</li>
                      <li>{t("rules.listItem1-8")}</li>
                      <li>{t("rules.listItem1-9")}</li>
                    </div>
                  </ol>
                  <li className={styles.listEl}>
                    <Title order={4} className={styles.title}>
                      {t("rules.listTitle2")}
                    </Title>
                  </li>
                  <ol className={styles.listItem}>
                    <div className={styles.listDist}>
                      <li>{t("rules.listItem2-1")}</li>
                      <div className={styles.listDist}>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-1-unordered-list-item-1")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-1-unordered-list-item-2")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-1-unordered-list-item-3")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-1-unordered-list-item-4")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-1-unordered-list-item-5")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-1-unordered-list-item-6")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-1-unordered-list-item-7")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-1-unordered-list-item-8")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-1-unordered-list-item-9")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-1-unordered-list-item-10")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-1-unordered-list-item-11")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-1-unordered-list-item-12")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-1-unordered-list-item-13")}
                        </Text>
                      </div>
                      <li>{t("rules.listItem2-2")}</li>
                      <li>{t("rules.listItem2-3")}</li>
                      <li>{t("rules.listItem2-4")}</li>
                      <li>{t("rules.listItem2-5")}</li>
                      <li>{t("rules.listItem2-6")}</li>
                      <div className={styles.listDist}>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-6-unordered-list-item-1")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-6-unordered-list-item-2")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-6-unordered-list-item-3")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-6-unordered-list-item-4")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-6-unordered-list-item-5")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-6-unordered-list-item-6")}
                        </Text>
                      </div>
                      <li>{t("rules.listItem2-7")}</li>
                      <li>{t("rules.listItem2-8")}</li>
                      <li>{t("rules.listItem2-9")}</li>
                      <li>{t("rules.listItem2-10")}</li>
                      <div className={styles.listDist}>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-10-unordered-list-item-1")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-10-unordered-list-item-2")}
                        </Text>
                      </div>
                      <li>{t("rules.listItem2-11")}</li>
                      <li>{t("rules.listItem2-12")}</li>
                      <li>{t("rules.listItem2-13")}</li>
                      <li>{t("rules.listItem2-14")}</li>
                      <li>{t("rules.listItem2-15")}</li>
                      <div className={styles.listDist}>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-15-unordered-list-item-1")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-15-unordered-list-item-2")}
                        </Text>
                      </div>
                      <li>{t("rules.listItem2-16")}</li>
                      <div className={styles.listDist}>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-16-unordered-list-item-1")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem2-16-unordered-list-item-2")}
                        </Text>
                      </div>
                      <li>{t("rules.listItem2-17")}</li>
                      <li>{t("rules.listItem2-18")}</li>
                      <li>{t("rules.listItem2-19")}</li>
                      <li>{t("rules.listItem2-20")}</li>
                    </div>
                  </ol>
                  <li className={styles.listEl}>
                    <Title order={4} className={styles.title}>
                      {t("rules.listTitle3")}
                    </Title>
                  </li>
                  <ol className={styles.listItem}>
                    <div className={styles.listDist}>
                      <li>{t("rules.listItem3-1")}</li>
                      <li>{t("rules.listItem3-2")}</li>
                      <li>{t("rules.listItem3-3")}</li>
                      <li>{t("rules.listItem3-4")}</li>
                      <li>{t("rules.listItem3-5")}</li>
                    </div>
                  </ol>
                  <li className={styles.listEl}>
                    <Title order={4} className={styles.title}>
                      {t("rules.listTitle4")}
                    </Title>
                  </li>
                  <ol className={styles.listItem}>
                    <div className={styles.listDist}>
                      <li>{t("rules.listItem4-1")}</li>
                      <div className={styles.listDist}>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem4-1-unordered-list-item-1")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem4-1-unordered-list-item-2")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem4-1-unordered-list-item-3")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem4-1-unordered-list-item-4")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem4-1-unordered-list-item-5")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem4-1-unordered-list-item-6")}
                        </Text>
                      </div>
                    </div>
                  </ol>
                  <li className={styles.listEl}>
                    <Title order={4} className={styles.title}>
                      {t("rules.listTitle5")}
                    </Title>
                  </li>
                  <ol className={styles.listItem}>
                    <div className={styles.listDist}>
                      <li>{t("rules.listItem5-1")}</li>
                      <div className={styles.listDist}>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-1-unordered-list-item-1")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-1-unordered-list-item-2")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-1-unordered-list-item-3")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-1-unordered-list-item-4")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-1-unordered-list-item-5")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-1-unordered-list-item-6")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-1-unordered-list-item-7")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-1-unordered-list-item-8")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-1-unordered-list-item-9")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-1-unordered-list-item-10")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-1-unordered-list-item-11")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-1-unordered-list-item-12")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-1-unordered-list-item-13")}
                        </Text>
                      </div>
                      <li>{t("rules.listItem5-2")}</li>
                      <div className={styles.listDist}>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-2-unordered-list-item-1")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-2-unordered-list-item-2")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-2-unordered-list-item-3")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-2-unordered-list-item-4")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-2-unordered-list-item-5")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-2-unordered-list-item-6")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-2-unordered-list-item-7")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-2-unordered-list-item-8")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-2-unordered-list-item-9")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-2-unordered-list-item-10")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-2-unordered-list-item-11")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-2-unordered-list-item-12")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-2-unordered-list-item-13")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-2-unordered-list-item-14")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem5-2-unordered-list-item-15")}
                        </Text>
                      </div>
                      <li>{t("rules.listItem5-3")}</li>
                      <li>{t("rules.listItem5-4")}</li>
                      <li>{t("rules.listItem5-5")}</li>
                      <li>{t("rules.listItem5-6")}</li>
                    </div>
                  </ol>
                  <li className={styles.listEl}>
                    <Title order={4} className={styles.title}>
                      {t("rules.listTitle6")}
                    </Title>
                  </li>
                  <ol className={styles.listItem}>
                    <div className={styles.listDist}>
                      <li>{t("rules.listItem6-1")}</li>
                      <div className={styles.listDist}>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem6-1-unordered-list-item-1")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem6-1-unordered-list-item-2")}
                        </Text>
                      </div>
                    </div>
                  </ol>
                  <li className={styles.listEl}>
                    <Title order={4} className={styles.title}>
                      {t("rules.listTitle7")}
                    </Title>
                  </li>
                  <ol className={styles.listItem}>
                    <div className={styles.listDist}>
                      <li>{t("rules.listItem7-1")}</li>
                      <div className={styles.listDist}>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem7-1-unordered-list-item-1")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem7-1-unordered-list-item-2")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem7-1-unordered-list-item-3")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem7-1-unordered-list-item-4")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem7-1-unordered-list-item-5")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem7-1-unordered-list-item-6")}
                        </Text>
                      </div>
                      <li>{t("rules.listItem7-2")}</li>
                      <div className={styles.listDist}>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem7-2-unordered-list-item-1")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem7-2-unordered-list-item-2")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem7-2-unordered-list-item-3")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem7-2-unordered-list-item-4")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem7-2-unordered-list-item-5")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem7-2-unordered-list-item-6")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem7-2-unordered-list-item-7")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem7-2-unordered-list-item-8")}
                        </Text>
                        <Text
                          color="secondary"
                          variant={textVariant}
                          className={styles.textLikeUnorderedList}
                        >
                          {t("rules.listItem7-2-unordered-list-item-9")}
                        </Text>
                      </div>
                      <li>{t("rules.listItem7-3")}</li>
                      <li>{t("rules.listItem7-4")}</li>
                      <li>{t("rules.listItem7-5")}</li>
                      <li>{t("rules.listItem7-6")}</li>
                    </div>
                  </ol>
                  <li className={styles.listEl}>
                    <Title order={4} className={styles.title}>
                      {t("rules.listTitle8")}
                    </Title>
                  </li>
                  <ol className={styles.listItem}>
                    <div className={styles.listDist}>
                      <li>{t("rules.listItem8-1")}</li>
                    </div>
                  </ol>
                </ol>
              </div>
              <div className={styles.listWrapper}>
                <Title order={isLaptop ? (isTablet ? 4 : 3) : 2}>
                  {t("fireSafety.title")}
                </Title>
                <Text color="secondary" variant={textVariant}>
                  {t("fireSafety.text")}
                </Text>
                <ol className={styles.listItem}>
                  <div className={styles.listDist}>
                    <li>{t("fireSafety.listItem1")}</li>
                    <li>{t("fireSafety.listItem2")}</li>
                    <li>{t("fireSafety.listItem3")}</li>
                    <li>{t("fireSafety.listItem4")}</li>
                    <li>{t("fireSafety.listItem5")}</li>
                    <li>{t("fireSafety.listItem6")}</li>
                    <li>{t("fireSafety.listItem7")}</li>
                    <li>{t("fireSafety.listItem8")}</li>
                    <li>{t("fireSafety.listItem9")}</li>
                    <div className={styles.listDist}>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem9-unordered-list-item-1")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem9-unordered-list-item-2")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem9-unordered-list-item-3")}
                      </Text>
                    </div>
                    <li>{t("fireSafety.listItem10")}</li>
                    <div className={styles.listDist}>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem10-unordered-list-item-1")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem10-unordered-list-item-2")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem10-unordered-list-item-3")}
                      </Text>
                    </div>
                    <li>{t("fireSafety.listItem11")}</li>
                    <div className={styles.listDist}>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem11-unordered-list-item-1")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem11-unordered-list-item-2")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem11-unordered-list-item-3")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem11-unordered-list-item-4")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem11-unordered-list-item-5")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem11-unordered-list-item-6")}
                      </Text>
                    </div>
                    <li>{t("fireSafety.listItem12")}</li>
                    <div className={styles.listDist}>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem12-unordered-list-item-1")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem12-unordered-list-item-2")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem12-unordered-list-item-3")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem12-unordered-list-item-4")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem12-unordered-list-item-5")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem12-unordered-list-item-6")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem12-unordered-list-item-7")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("fireSafety.listItem12-unordered-list-item-8")}
                      </Text>
                    </div>
                  </div>
                </ol>
                <Text variant={isLaptop ? "boldL" : "boldM"}>
                  {t("fireSafety.warning")}
                </Text>
              </div>
              <div className={styles.listWrapper}>
                <Title order={isLaptop ? (isTablet ? 4 : 3) : 2}>
                  {t("personalSafety.title")}
                </Title>
                <ol className={styles.listItem}>
                  <div className={styles.listDist}>
                    <li>{t("personalSafety.listItem1")}</li>
                    <div className={styles.listDist}>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem1-unordered-list-item-1")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem1-unordered-list-item-2")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem1-unordered-list-item-3")}
                      </Text>
                    </div>
                    <li>{t("personalSafety.listItem2")}</li>
                    <div className={styles.listDist}>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem2-unordered-list-item-1")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem2-unordered-list-item-2")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem2-unordered-list-item-3")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem2-unordered-list-item-4")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem2-unordered-list-item-5")}
                      </Text>
                    </div>
                    <li>{t("personalSafety.listItem3")}</li>
                    <Text color="secondary" variant={textVariant}>
                      {t("personalSafety.listItem3-text1")}
                    </Text>
                    <div className={styles.listDist}>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem3-unordered-list-item-1")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem3-unordered-list-item-2")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem3-unordered-list-item-3")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem3-unordered-list-item-4")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem3-unordered-list-item-5")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem3-unordered-list-item-6")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem3-unordered-list-item-7")}
                      </Text>
                    </div>
                    <li>{t("personalSafety.listItem4")}</li>
                    <div className={styles.listDist}>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem4-unordered-list-item-1")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem4-unordered-list-item-2")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem4-unordered-list-item-3")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem4-unordered-list-item-4")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem4-unordered-list-item-5")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem4-unordered-list-item-6")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem4-unordered-list-item-7")}
                      </Text>
                    </div>
                    <li>{t("personalSafety.listItem5")}</li>
                    <Text color="secondary" variant={textVariant}>
                      {t("personalSafety.listItem5-text1")}
                    </Text>
                    <Text color="secondary" variant={textVariant}>
                      {t("personalSafety.listItem5-text2")}
                    </Text>
                    <div className={styles.listDist}>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem5-unordered-list-item-1")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem5-unordered-list-item-2")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem5-unordered-list-item-3")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem5-unordered-list-item-4")}
                      </Text>
                    </div>
                    <li>{t("personalSafety.listItem6")}</li>
                    <Text color="secondary" variant={textVariant}>
                      {t("personalSafety.listItem6-text1")}
                    </Text>
                    <div className={styles.listDist}>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem6-unordered-list-item-1")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem6-unordered-list-item-2")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem6-unordered-list-item-3")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem6-unordered-list-item-4")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem6-unordered-list-item-5")}
                      </Text>
                    </div>
                    <li>{t("personalSafety.listItem7")}</li>
                    <Text color="secondary" variant={textVariant}>
                      {t("personalSafety.listItem7-text1")}
                    </Text>
                    <Text color="secondary" variant={textVariant}>
                      {t("personalSafety.listItem7-text2")}
                    </Text>
                    <div className={styles.listDist}>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem7-unordered-list-item-1")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem7-unordered-list-item-2")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem7-unordered-list-item-3")}
                      </Text>
                    </div>
                    <Text color="secondary" variant={textVariant}>
                      {t("personalSafety.listItem7-text3")}
                    </Text>
                    <li>{t("personalSafety.listItem8")}</li>
                    <div className={styles.listDist}>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem8-unordered-list-item-1")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem8-unordered-list-item-2")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem8-unordered-list-item-3")}
                      </Text>
                    </div>
                    <Text color="secondary" variant={textVariant}>
                      {t("personalSafety.listItem8-text1")}
                    </Text>
                    <div className={styles.listDist}>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem8-unordered-list-item-4")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem8-unordered-list-item-5")}
                      </Text>
                      <Text
                        color="secondary"
                        variant={textVariant}
                        className={styles.textLikeUnorderedList}
                      >
                        {t("personalSafety.listItem8-unordered-list-item-6")}
                      </Text>
                    </div>
                  </div>
                </ol>
                <Text variant={isLaptop ? "boldL" : "boldM"}>
                  {t("personalSafety.warning1")}
                </Text>
                <Text variant={isLaptop ? "boldL" : "boldM"}>
                  {t("personalSafety.warning2")}
                </Text>
                <Text variant={isLaptop ? "normalL" : "normalL"}>
                  {t("personalSafety.description")}
                </Text>
              </div>
            </div>

            <NextLink passHref href="/">
              <Button
                uppercase
                fullWidth={isTablet ? true : false}
                size="l"
                color="secondaryDark"
              >
                {t("toMain")}
              </Button>
            </NextLink>
          </div>
        </Container>
      </Main>
      <Footer chooseCity={false} />
    </>
  );
};
